/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		403: typeof import('./src/components/ErrorMessage/403.vue')['default']
		404: typeof import('./src/components/ErrorMessage/404.vue')['default']
		500: typeof import('./src/components/ErrorMessage/500.vue')['default']
		ElAlert: typeof import('element-plus/es')['ElAlert']
		ElAside: typeof import('element-plus/es')['ElAside']
		ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
		ElBadge: typeof import('element-plus/es')['ElBadge']
		ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
		ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
		ElButton: typeof import('element-plus/es')['ElButton']
		ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
		ElContainer: typeof import('element-plus/es')['ElContainer']
		ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
		ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
		ElDialog: typeof import('element-plus/es')['ElDialog']
		ElDivider: typeof import('element-plus/es')['ElDivider']
		ElDrawer: typeof import('element-plus/es')['ElDrawer']
		ElDropdown: typeof import('element-plus/es')['ElDropdown']
		ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
		ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
		ElFooter: typeof import('element-plus/es')['ElFooter']
		ElForm: typeof import('element-plus/es')['ElForm']
		ElFormItem: typeof import('element-plus/es')['ElFormItem']
		ElHeader: typeof import('element-plus/es')['ElHeader']
		ElIcon: typeof import('element-plus/es')['ElIcon']
		ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
		ElInput: typeof import('element-plus/es')['ElInput']
		ElMain: typeof import('element-plus/es')['ElMain']
		ElMenu: typeof import('element-plus/es')['ElMenu']
		ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
		ElPopover: typeof import('element-plus/es')['ElPopover']
		ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
		ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
		ElSwitch: typeof import('element-plus/es')['ElSwitch']
		ElTabPane: typeof import('element-plus/es')['ElTabPane']
		ElTabs: typeof import('element-plus/es')['ElTabs']
		ElTooltip: typeof import('element-plus/es')['ElTooltip']
		ElUpload: typeof import('element-plus/es')['ElUpload']
		Img: typeof import('./src/components/Upload/Img.vue')['default']
		Imgs: typeof import('./src/components/Upload/Imgs.vue')['default']
		RouterLink: typeof import('vue-router')['RouterLink']
		RouterView: typeof import('vue-router')['RouterView']
		SelectFilter: typeof import('./src/components/SelectFilter/index.vue')['default']
		SelectIcon: typeof import('./src/components/SelectIcon/index.vue')['default']
		SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
		SwitchDark: typeof import('./src/components/SwitchDark/index.vue')['default']
		TreeFilter: typeof import('./src/components/TreeFilter/index.vue')['default']
		WangEditor: typeof import('./src/components/WangEditor/index.vue')['default']
	}
}
