/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    403: typeof import('./src/components/ErrorMessage/403.vue')['default']
    404: typeof import('./src/components/ErrorMessage/404.vue')['default']
    500: typeof import('./src/components/ErrorMessage/500.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/Test.vue')['default']
  }
}
